### ISSUE TITLE
in Getting Started, the Key material is required in the Adding existing keys section

### ISSUE THREAD

**Issue by powellquiring** [IBM-Bluemix-Docs/keymgmt#12]
Adding existing keys
...

Key material | Only required if you  are adding an existing key. ...

- - - - - - 

My understanding is the point of BYOK is to bring the key material into key protect.  Remove the sentence "Only required if you  are adding an existing key" or replace it with: "Enter your key material

**Comment by ccbarragan** [comment]
Thanks for your feedback!

I've added a change based on your request. 

> Key material | Only required if you are adding an existing key. The key material can be any type of data, such as a symmetric key, that you want to store in the Key Protect service.

is now

> Key material | The key material, such as a symmetric key, that you want to store in the Key Protect service.

You can take a look at the [Getting Started page](https://console.bluemix.net/docs/services/keymgmt/index.html#getting-started-with-key-protect) (might take between 15-30 minutes) to see the new changes.
