### ISSUE TITLE
In Getting Started add a link to the docs

### ISSUE THREAD

**Issue by powellquiring** [IBM-Bluemix-Docs/keymgmt#13]
The Getting Started page add a link to the docs, specifically: https://console.bluemix.net/docs/services/keymgmt/index.html#getting-started-with-key-protect 

I would add it to the first paragraph.  It could be added to the What's next section as well.

**Comment by ccbarragan** [comment]
Hi @powellquiring, thanks for your feedback!

It seems that you'd like to see a link to the Key Protect docs in the Key Protect Getting Started page -- Is this correct? If so, we typically do not add a link to a page within a page.

Can you clarify your request?

Thanks!

**Comment by powellquiring** [comment]
On the getting started page https://console.bluemix.net/docs/services/keymgmt/index.html#getting-started-with-key-protect my desired next step was to read the docs and I didn't notice a way to get to them.

**Comment by ccbarragan** [comment]
I've added a quick fix based on your request. Thanks again for bringing this up.

![screen shot 2018-07-02 at 2 19 02 pm](https://user-images.githubusercontent.com/28902259/42182174-fc5cdcf0-7e02-11e8-8a99-c4f14f78d704.png)

**Comment by ccbarragan** [comment]
@powellquiring Can you validate and close? Thanks!

**Comment by powellquiring** [comment]
The "check out the integrations doc." link is broken

![kpbrokenlink](https://user-images.githubusercontent.com/6932057/42391978-0d0ab9e0-8106-11e8-8a38-3e6108c22e78.png)
![brokendestination](https://user-images.githubusercontent.com/6932057/42392039-3d67be94-8106-11e8-9d6f-50f9ca81a8bf.png)

**Comment by ccbarragan** [comment]
Fixed 👍
